# This is a basic workflow to help you get started with Actions

name: 自动更新

# Controls when the workflow will run
on:
  workflow_dispatch: # 手动触发
  schedule: # 计划任务触发
    - cron: '0 9 */15 * *'
  # Triggers the workflow on push or pull request events but only for the "main" branch
  #push:
  #  branches: [ "main" ]
  #pull_request:
  #  branches: [ "main" ]
permissions:
  contents: write

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  update:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    
    env:
      ProjRoot: .

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: 更新Telegram
        run: |
          ProjRoot=$PWD
          cd $ProjRoot/Surge/Ruleset/Extra/Telegram/
          wget https://cdn.jsdelivr.net/gh/Loyalsoldier/surge-rules@release/telegramcidr.txt -O telegramcidr.txt
          sed -ri "s/([0-9])$/\1,no-resolve/g" ./telegramcidr.txt
          cat Telegram.list telegramcidr.txt | sort | uniq > uniq.txt
          mv uniq.txt Telegram.list
          git add Telegram.list

      - name: 提交变更
        run: |
           git config --local user.email "ciaoly@github.com"
           git config --local user.name "ciaoly"
           git commit -m "文件更新于$(date "+%Y-%m-%d %H:%M:%S")"
         
      # 更新至远程github代码仓库中
      - name: 推送变更
        uses:  ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.SURGE_RULE_GIT_KEY }}
          branch: main
